import {BlockButton, FormBlock} from '@/components';
import s from '@/styles/HomePage.module.scss';
import {IBlock} from '@/types';
import useWebSocket from '@/useWebSocket';
import Head from 'next/head';
import Image from 'next/image';
import {useEffect, useMemo, useRef, useState} from 'react';

const BLOCKS: IBlock[] = [
  {name: 'block1', isOpen: false},
  {name: 'block2', isOpen: false},
  {name: 'block3', isOpen: false},
]

const url = 'wss://taxivoshod.ru:8999';

export default function HomePage() {

  const firstEffectRan = useRef(false);

  const wsInstance = useMemo(() => typeof window != 'undefined' ? new WebSocket(url) : null, []);
  const {wsState, error, subscribe, unsubscribe, setFocus, setBlur} = useWebSocket(wsInstance);
  const [activeBlock, setActiveBlock] = useState<IBlock[]>(BLOCKS);

  useEffect(() => {
    if (firstEffectRan.current) {
      if (wsInstance) wsInstance.onopen = () => console.log('[open] ws connection started');
      if (wsInstance) wsInstance.onclose = () => console.log('[close] ws connection closed');
    }
    return () => {
      if (firstEffectRan.current) wsInstance?.close();
      firstEffectRan.current = true;
    }
  }, []);

  function toggleBlock(name: string) {
    setActiveBlock((v) => v.map((item) => item.name === name ? {...item, isOpen: !item.isOpen} : item));
  }

  return (
    <>
      <Head>
        <title>taxi voshod test task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>

        <div className={s.logo__wrapper} >
          <Image src="/logo.svg" alt="company Logo" className={s.logo} width={275} height={136} priority />
        </div>
        <div className={s.buttons__wrapper} >
          {
            activeBlock.map((block) =>
              <BlockButton key={block.name} block={block} clickHandler={() => toggleBlock(block.name)} />
            )
          }
        </div>
        <div className={s.blocks__wrapper}>
          {
            activeBlock.map((block) =>
              block.isOpen &&
              <FormBlock key={block.name}
                block={block.name}
                wsState={wsState[block.name]}
                subscribe={subscribe}
                unsubscribe={unsubscribe}
                setBlur={setBlur}
                setFocus={setFocus}
              />
            )
          }
        </div>

      </main>
    </>
  )
}
